name: xxp
channels:
  - conda-forge
  - defaults
dependencies:
  - _py-xgboost-mutex=2.0
  - brotli=1.2.0
  - brotli-bin=1.2.0
  - bzip2=1.0.8
  - ca-certificates=2025.11.4
  - cloudpickle=3.1.2
  - colorama=0.4.6
  - contourpy=1.3.3
  - cycler=0.12.1
  - fonttools=4.60.1
  - freetype=2.14.1
  - icu=75.1
  - joblib=1.5.2
  - kiwisolver=1.4.9
  - kmedoids=0.5.4
  - lcms2=2.17
  - lerc=4.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.2.0
  - libbrotlidec=1.2.0
  - libbrotlienc=1.2.0
  - libcblas=3.9.0
  - libcxx=21.1.5
  - libdeflate=1.25
  - libexpat=2.7.1
  - libffi=3.5.2
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - libjpeg-turbo=3.1.2
  - liblapack=3.9.0
  - liblzma=5.8.1
  - libopenblas=0.3.30
  - libpng=1.6.50
  - libsqlite=3.51.0
  - libtiff=4.7.1
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxgboost=3.0.3
  - libzlib=1.3.1
  - llvm-openmp=21.1.5
  - llvmlite=0.45.1
  - matplotlib-base=3.10.7
  - munkres=1.1.4
  - ncurses=6.5
  - numba=0.62.1
  - numpy=2.3.4
  - openjpeg=2.5.4
  - openssl=3.6.0
  - packaging=25.0
  - patsy=1.0.2
  - pillow=12.0.0
  - pip=25.2
  - prince=0.13.0
  - pthread-stubs=0.4
  - pyale=1.2.0
  - pyparsing=3.2.5
  - python=3.11.14
  - python-dateutil=2.9.0.post0
  - python-tzdata=2025.2
  - python_abi=3.11
  - pytz=2025.2
  - qhull=2020.2
  - readline=8.2
  - scikit-learn=1.7.2
  - scipy=1.16.3
  - setuptools=80.9.0
  - shap=0.48.0
  - six=1.17.0
  - slicer=0.0.8
  - statsmodels=0.14.5
  - threadpoolctl=3.6.0
  - tk=8.6.13
  - tqdm=4.67.1
  - typing_extensions=4.15.0
  - tzdata=2025b
  - unicodedata2=17.0.0
  - wheel=0.45.1
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - zlib-ng=2.2.5
  - zstd=1.5.7
  - pip:
      - altair==4.2.2
      - attrs==25.4.0
      - entrypoints==0.4
      - imbalanced-learn==0.14.0
      - jinja2==3.1.6
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - kneed==0.8.5
      - markupsafe==3.0.3
      - networkx==3.5
      - pandas==1.5.3
      - pandas-flavor==0.7.0
      - pingouin==0.5.5
      - referencing==0.37.0
      - rpds-py==0.28.0
      - seaborn==0.13.2
      - tabulate==0.9.0
      - toolz==1.1.0
      - xarray==2024.3.0
      - xgboost==3.0.3